[tool.poetry]
name = "course-work-0-2"
version = "0.1.0"
description = ""
authors = ["konovalova"]
readme = "README.md"
packages = [{include = "course_work_0"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
